version: '3.8'
services:
  deno:
    build: .
    volumes:
      - './:/app:rw,consistent'
    ports:
      - 8080:1337
    depends_on:
      - postgres
  postgres:
    image: 'postgres:alpine'
    volumes:
      - db-data:/var/lib/postgres/data'
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgres/data/pgdata
      - POSTGRES_DB=deno
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db-data:
