image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"
  only:
    - master

.docker-login:
  before_script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

build_back:
  stage: build
  extends: .docker-login
  script:
    - docker build -t elie91/sportunities-pa-api -f Dockerfile.prod  .
    - docker push elie91/sportunities-pa-api
  only:
    - master

deploy_prod:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo "Deploy to production server"
    - echo "$GCP_SERVICE_KEY" > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud config set compute/zone europe-west4-a
    - gcloud container clusters get-credentials sportnunities
    - gcloud auth configure-docker
    - kubectl apply -f k8s/
    - kubectl rollout restart deployment/server-deployment
    - kubectl rollout restart deployment/client-deployment
  environment:
    name: prod
    url: https://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_NAME.$MY_DOMAIN
  only:
    - master
