controllers_front:
    prefix: '/{_locale}'
    name_prefix: 'front_'
    resource: ../../src/Controller/Front
    type: annotation
    requirements:
        _locale: 'en|fr|'

controllers_back:
    prefix: 'admin'
    name_prefix: 'back_'
    resource: ../../src/Controller/Back
    type: annotation

security_controller:
    prefix: '/{_locale}'
    resource: ../../src/Controller/SecurityController.php
    type: annotation