image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

.docker-login:
  before_script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

test:
  stage: test
  script: echo "Running tests"
  only:
    - master

build_front:
  stage: build
  extends: .docker-login
  script:
    - docker build -t elie91/sportunities-pa-client -f Dockerfile.prod ./
    - docker push elie91/sportunities-pa-client
  only:
    - master