FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN yarn install
ARG REACT_APP_API_URL=/api
COPY . .
RUN yarn run build

FROM nginx
EXPOSE 3000
COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /app/build /usr/share/nginx/html