services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Fidry\AliceDataFixtures\LoaderInterface: '@fidry_alice_data_fixtures.doctrine.persister_loader'
