apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: sportunities-com-tls
spec:
  secretName: sportunities-com-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sportunities.com
  dnsNames:
    - sportunities.com
    - www.sportunities.com