apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: elie91/sportunities-pa-client
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_API_URL
            value: /api
#          - name: REACT_APP_MERCURE_HUB_URL
#            value: http://localhost:8080
