apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
# k8s must find a storage instance that meets the requirements
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # must find stokage instance that has 2g
      storage: 2Gi
    # see readme for storageClassName