install:
	composer install

test_unit:
	php bin/phpunit tests/Service

test_integration:
	php bin/phpunit tests/Integration

test_functional:
	php bin/phpunit tests/Controller

test: test_unit test_integration test_functional


