security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            logout:
                path: security_logout
                target: security_login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 7257600
                path:     /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_GUEST]

    access_control:
        - { path: ^/admin, roles: ROLE_GUEST }