twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        -   'bootstrap_4_layout.html.twig'
        -   'form/quills.html.twig'
    globals:
        picture_path: "build/images/users/"
