# Generated by Django 3.2.1 on 2021-05-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210505_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('manager', 'manager'), ('student', 'student')], default='student', max_length=7),
        ),
    ]
