# Generated by Django 3.2.1 on 2021-05-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='promotion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='web.promotion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254,
                                    unique=True, verbose_name='email address'),
        ),
    ]
