doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '12'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        dql:
            string_functions:
                TO_TSQUERY: App\Doctrine\DQL\ToTSQueryFunction
                TO_TSVECTOR: App\Doctrine\DQL\ToTSVectorFunction
                FULL_TEXT_SEARCH: App\Doctrine\DQL\FullTextSearchFunction
                UNACCENT: App\Doctrine\DQL\UnaccentFunction
                JSON_CONTAINS: App\Doctrine\DQL\JsonContainsFunction
