parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(SENDINBLUE_APIKEY): ''
  env(OVERRIDE_EMAIL_TO): null

sendinblue_api:
  endpoints: [ 'smtp' ]
  key: '%env(resolve:SENDINBLUE_APIKEY)%'