version: "3.8"
services:
  postgres:
    image: "postgres:12-alpine"
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgres/data/pgdata
      - POSTGRES_DB=sports
      - POSTGRES_USER=sports
      - POSTGRES_PASSWORD=rKQbt86bt3zt44aB
  api:
    build:
      context: ./api
      target: api_development
    volumes:
      - /usr/src/api/node_modules
      - ./api:/usr/src/api:rw
    environment:
      - JWT_SECRET="ShKz495hAk8Cbh8d"
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=sports
      - POSTGRES_PORT=5432
      - POSTGRES_USER=sports
      - POSTGRES_PASSWORD=rKQbt86bt3zt44aB
      - NODE_AWS_ACCESS_KEY=AKIAQ2YNHC7MDNVVPUEF
      - NODE_AWS_SECRET_KEY=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
      - NODE_S3_BUCKET_NAME=sportunities-bucket-pa
      - MERCURE_PORT=80
      - MERCURE_HOST=caddy
      - MERCURE_BEARER=eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiaHR0cHM6Ly9leGFtcGxlLmNvbS9teS1wcml2YXRlLXRvcGljIiwie3NjaGVtZX06Ly97K2hvc3R9L2RlbW8vYm9va3Mve2lkfS5qc29ubGQiLCIvLndlbGwta25vd24vbWVyY3VyZS9zdWJzY3JpcHRpb25zey90b3BpY317L3N1YnNjcmliZXJ9Il0sInBheWxvYWQiOnsidXNlciI6Imh0dHBzOi8vZXhhbXBsZS5jb20vdXNlcnMvZHVuZ2xhcyIsInJlbW90ZUFkZHIiOiIxMjcuMC4wLjEifX19.z5YrkHwtkz3O_nOnhC_FP7_bmeISe3eykAkGbAl5K7c
    ports:
      - 3001:3001
    depends_on:
      - caddy
      - postgres

  caddy:
    image: dunglas/mercure
    environment:
      - MERCURE_PUBLISHER_JWT_KEY=!ChangeMe!
      - MERCURE_SUBSCRIBER_JWT_KEY=!ChangeMe!
      - DEBUG=debug # Enable the debug mode. You should not enable it in production!
      - SERVER_NAME=:80
      - MERCURE_EXTRA_DIRECTIVES=cors_allowed_origins *\npublish_allowed_origins http://localhost:1337 https://localhost:1338
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "3002:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  client:
    build:
      context: ./client
      target: client_development
      cache_from:
        - ${CLIENT_IMAGE:-quay.io/api-platform/client}
    image: ${CLIENT_IMAGE:-quay.io/api-platform/client}
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_MERCURE_HUB_URL=http://localhost:3002
    volumes:
      - /usr/src/api/node_modules
      - ./client:/usr/src/client:rw
    ports:
      - 8080:3000
volumes:
  db-data:
  caddy_data:
  caddy_config:
